/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student.grade.tracker;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane; 
import java.time.*;  
import java.util.*; 
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.util.Date;
/**
 *
 * @author morayyajain
 */
public class AddAssignment extends javax.swing.JFrame {
	static final String DB_URL = "jdbc:mysql://localhost/studentgrade";
	static final String USER = "root";
	static final String PASS = "root@123";
	
	/**
	 * Creates new form Assignment
	 */
	public AddAssignment() {
		initComponents();
		jLabel5.setVisible(false);
		jDateChooser2.setVisible(false);
		jLabel6.setVisible(false);
		jSpinner1.setVisible(false);
		jLabel7.setVisible(false);
		jSpinner2.setVisible(false);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jTextField1 = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                jTextField2 = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                jDateChooser1 = new com.toedter.calendar.JDateChooser();
                jLabel4 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jLabel5 = new javax.swing.JLabel();
                jDateChooser2 = new com.toedter.calendar.JDateChooser();
                jSpinner1 = new javax.swing.JSpinner();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jSpinner2 = new javax.swing.JSpinner();
                jComboBox1 = new javax.swing.JComboBox<>();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setText("Assignment Code");

                jLabel2.setText("Subject");

                jLabel3.setText("Deadline");

                jLabel4.setText("Submitted?");

                jButton1.setText("Back");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jButton2.setText("Exit");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                jButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
                jButton3.setText("Add");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                jLabel5.setText("Date Submitted");

                jLabel6.setText("Max Marks");

                jLabel7.setText("Marks Obtained");

                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
                jComboBox1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jComboBox1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(176, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(285, 285, 285))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jLabel1)
                                                                        .addGap(35, 35, 35)
                                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(jLabel4))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addGap(170, 170, 170))))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(289, 289, 289)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jSpinner2)
                                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addGap(50, 50, 50))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		int a=JOptionPane.showConfirmDialog(null,"Are you sure you want to close?","Select",JOptionPane.YES_NO_OPTION);
                if(a==0){
                        System.exit(0);
                }
                // TODO add your handling code here:
        }//GEN-LAST:event_jButton2ActionPerformed

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		setVisible(false);
                new Homepage().setVisible(true);
                // TODO add your handling code here:
        }//GEN-LAST:event_jButton1ActionPerformed

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
	        String submitted=(String)jComboBox1.getSelectedItem();
		String progress="";
		if(submitted=="Yes"){
			
			if(jDateChooser1.getDate()==null || jDateChooser2.getDate()==null) {
			JOptionPane.showMessageDialog(null,"Please fill in all the details");
			}
			else{
				String code=jTextField1.getText();
				String subject=jTextField2.getText();
				String deadline=(new java.text.SimpleDateFormat("dd-MM-yyyy")).format(jDateChooser1.getDate());
				String datesubmitted=(new java.text.SimpleDateFormat("dd-MM-yyyy")).format(jDateChooser2.getDate());
				int imaxmarks=(int) jSpinner1.getValue();
				int iobtained=(int) jSpinner2.getValue();
				String maxmarks=Integer.toString(imaxmarks);  
				String obtained=Integer.toString(iobtained);
				boolean result1 = subject.matches("[a-zA-Z ]+");

				if (result1 && maxmarks.matches("[0-9]+") && obtained.matches("[0-9]+")){
					
					try{
						SimpleDateFormat sdformat = new SimpleDateFormat("dd-MM-yyyy");	
						Date d1 = sdformat.parse(deadline);
						Date d2 = sdformat.parse(datesubmitted);	
					
					String dd1=(new java.text.SimpleDateFormat("dd")).format(jDateChooser2.getDate());
					String mm1=(new java.text.SimpleDateFormat("MM")).format(jDateChooser2.getDate());
					String yyyy1=(new java.text.SimpleDateFormat("yyyy")).format(jDateChooser2.getDate());
					int ddd1=Integer.parseInt(dd1);
					int mmm1=Integer.parseInt(mm1);
					int yyyyy1=Integer.parseInt(yyyy1);	
					LocalDate dob1 = LocalDate.of(yyyyy1,mmm1,ddd1);  
					LocalDate curDate1 = LocalDate.now();  
					Period period1 = Period.between(dob1, curDate1);  
					String ab1=Integer.toString(period1.getDays()); 	
					int ab=Integer.parseInt(ab1);
					
	
					if (code.length() <=0 || subject.length() <=0 || imaxmarks<=0 || iobtained<=0 || imaxmarks<iobtained || ab<0){
					
						JOptionPane.showMessageDialog(null,"Invalid");
					}
					else{
						try(Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
					Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);	
							) { 
					String sql = "select * from Assignment where code='"+code+"'";
                                        ResultSet rs= stmt.executeQuery(sql);
					
					if (!rs.first()){
						
						try(Connection con = DriverManager.getConnection(DB_URL, USER, PASS);
					Statement stm = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);	
					)    { 
							if(d1.compareTo(d2) < 0){
							progress="Late";
						}
						else{	
							progress="On time";
						}
					String sq = "Insert INTO Assignment VALUES('"+code+"','"+subject+"','"+deadline+"','"+submitted+"','"+datesubmitted+"','"+maxmarks+"','"+obtained+"','"+progress+"')";
                                        stm.executeUpdate(sq);
					
					jTextField1.setText("");
					jTextField2.setText("");
					jDateChooser1.setDate(null);
					jDateChooser2.setDate(null);
					jSpinner1.setValue(0);
					jSpinner2.setValue(0);
					jComboBox1.setSelectedItem("No");
					
					jLabel5.setVisible(false);
					jDateChooser2.setVisible(false);
					jLabel6.setVisible(false);
					jSpinner1.setVisible(false);
					jLabel7.setVisible(false);
					jSpinner2.setVisible(false);
					JOptionPane.showMessageDialog(null,"Successfully Added");
						
					}
						catch (SQLException e) { 
					e.printStackTrace();
						}
					}
					else{
						JOptionPane.showMessageDialog(null,"Assignment code already exists");
					}
						
					}
					catch (SQLException e) {
							e.printStackTrace();
						}	
					}
					}
					catch (Exception e){	
				}
				}
				else{
					JOptionPane.showMessageDialog(null,"Invalid Data");
				}
			

        }//GEN-LAST:event_jButton3ActionPerformed
			}	
		else       {
			if(jDateChooser1.getDate()==null) {
				JOptionPane.showMessageDialog(null,"Please fill in all the details");
			}
			else{
				String code=jTextField1.getText();
				String subject=jTextField2.getText();
				String deadline=(new java.text.SimpleDateFormat("dd-MM-yyyy")).format(jDateChooser1.getDate());
				String datesubmitted="NA";
				String maxmarks="NA";
				String obtained="NA";
				progress="Not Submitted";
				boolean result1 = subject.matches("[a-zA-Z ]+");

				if (result1){
					
					if (code.length() <=0 || subject.length() <=0){
					
						JOptionPane.showMessageDialog(null,"Please fill in all the details");
					}
					
					else{
						
						try(Connection connnn = DriverManager.getConnection(DB_URL, USER, PASS);
						Statement stmtt = connnn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);	
							) { 
					String sqll = "select * from Assignment where code='"+code+"'";
                                        ResultSet rss= stmtt.executeQuery(sqll);
					
					if (!rss.first()){
						
						try(Connection co = DriverManager.getConnection(DB_URL, USER, PASS);
					Statement st = co.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);	
					)    { 
							
					String s = "Insert INTO Assignment VALUES('"+code+"','"+subject+"','"+deadline+"','"+submitted+"','"+datesubmitted+"','"+maxmarks+"','"+obtained+"','"+progress+"')";
                                        st.executeUpdate(s);
					
					jTextField1.setText("");
					jTextField2.setText("");
					jDateChooser1.setDate(null);

					JOptionPane.showMessageDialog(null,"Successfully Added");
						
					}
						catch (SQLException e) { 
					e.printStackTrace();
						}
						
					}
					else{
						JOptionPane.showMessageDialog(null,"Assignment code already exists");
					}
					
					
				}
						catch (SQLException e) { 
					e.printStackTrace();
						}	
				
			}
			
		}
				else{
					JOptionPane.showMessageDialog(null,"Invalid Data");
				}
			}
		}
			
	}

        private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
		String submitted=(String)jComboBox1.getSelectedItem();
		if(submitted=="Yes"){
			jLabel5.setVisible(true);
		jDateChooser2.setVisible(true);
		jLabel6.setVisible(true);
		jSpinner1.setVisible(true);
		jLabel7.setVisible(true);
		jSpinner2.setVisible(true);
		}
		else{
			jLabel5.setVisible(false);
		jDateChooser2.setVisible(false);
		jLabel6.setVisible(false);
		jSpinner1.setVisible(false);
		jLabel7.setVisible(false);
		jSpinner2.setVisible(false);
		}
                
        }//GEN-LAST:event_jComboBox1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AddAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AddAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AddAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AddAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AddAssignment().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JComboBox<String> jComboBox1;
        private com.toedter.calendar.JDateChooser jDateChooser1;
        private com.toedter.calendar.JDateChooser jDateChooser2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JSpinner jSpinner1;
        private javax.swing.JSpinner jSpinner2;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField2;
        // End of variables declaration//GEN-END:variables
}
