/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student.grade.tracker;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane; 
import java.time.*;  
import java.util.*; 
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.util.Date;

/**
 *
 * @author morayyajain
 */
public class EditExamination extends javax.swing.JFrame {
	static final String DB_URL = "jdbc:mysql://localhost/studentgrade";
	static final String USER = "root";
	static final String PASS = "root@123";
	/**
	 * Creates new form Assignment
	 */
	public EditExamination() {
		initComponents();
		jButton6.setVisible(false);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel3 = new javax.swing.JLabel();
                jDateChooser1 = new com.toedter.calendar.JDateChooser();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jSpinner1 = new javax.swing.JSpinner();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jSpinner2 = new javax.swing.JSpinner();
                jLabel1 = new javax.swing.JLabel();
                jTextField1 = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                jTextField2 = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                jDateChooser2 = new com.toedter.calendar.JDateChooser();
                jButton4 = new javax.swing.JButton();
                jButton5 = new javax.swing.JButton();
                jButton6 = new javax.swing.JButton();
                jSpinner3 = new javax.swing.JSpinner();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jSpinner4 = new javax.swing.JSpinner();
                jLabel5 = new javax.swing.JLabel();
                jTextField3 = new javax.swing.JTextField();
                jLabel10 = new javax.swing.JLabel();
                jTextField4 = new javax.swing.JTextField();
                jButton7 = new javax.swing.JButton();

                jLabel3.setText("Date of Exam");

                jButton1.setText("Back");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jButton2.setText("Exit");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                jButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
                jButton3.setText("Add");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                jLabel6.setText("Max Marks");

                jLabel7.setText("Marks Obtained");

                jLabel1.setText("Examination Code");

                jLabel2.setText("Subject");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel4.setText("Date of Exam");

                jButton4.setText("Back");
                jButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton4ActionPerformed(evt);
                        }
                });

                jButton5.setText("Exit");
                jButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton5ActionPerformed(evt);
                        }
                });

                jButton6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
                jButton6.setText("Edit");
                jButton6.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton6ActionPerformed(evt);
                        }
                });

                jLabel8.setText("Max Marks");

                jLabel9.setText("Marks Obtained");

                jLabel5.setText("Examination Code");

                jLabel10.setText("Subject");

                jButton7.setText("Search");
                jButton7.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton7ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(112, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(35, 35, 35)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel10)
                                                        .addComponent(jLabel4))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(57, 57, 57)
                                .addComponent(jButton7)
                                .addGap(102, 102, 102))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel9))
                                                .addGap(74, 74, 74)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jSpinner4)
                                                        .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(32, 32, 32)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(68, 68, 68)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5)
                                .addContainerGap(91, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                setVisible(false);
                new Homepage().setVisible(true);
                // TODO add your handling code here:
        }//GEN-LAST:event_jButton1ActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                int a=JOptionPane.showConfirmDialog(null,"Are you sure you want to close?","Select",JOptionPane.YES_NO_OPTION);
                if(a==0){
                        System.exit(0);
                }
                // TODO add your handling code here:
        }//GEN-LAST:event_jButton2ActionPerformed

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

                if(jDateChooser1.getDate()==null) {
                        JOptionPane.showMessageDialog(null,"Please fill in all the details");
                }
                else            {
                        String code=jTextField1.getText();
                        String subject=jTextField2.getText();
                        String dateofexam=(new java.text.SimpleDateFormat("dd-MM-yyyy")).format(jDateChooser1.getDate());
                        int imaxmarks=(int) jSpinner1.getValue();
                        int iobtained=(int) jSpinner2.getValue();
                        String maxmarks=Integer.toString(imaxmarks);
                        String obtained=Integer.toString(iobtained);
                        boolean result1 = subject.matches("[a-zA-Z ]+");

                        if (result1 && maxmarks.matches("[0-9]+") && obtained.matches("[0-9]+")){

                                try{
                                        SimpleDateFormat sdformat = new SimpleDateFormat("dd-MM-yyyy");
                                        Date d1 = sdformat.parse(dateofexam);

                                        String dd1=(new java.text.SimpleDateFormat("dd")).format(jDateChooser1.getDate());
                                        String mm1=(new java.text.SimpleDateFormat("MM")).format(jDateChooser1.getDate());
                                        String yyyy1=(new java.text.SimpleDateFormat("yyyy")).format(jDateChooser1.getDate());
                                        int ddd1=Integer.parseInt(dd1);
                                        int mmm1=Integer.parseInt(mm1);
                                        int yyyyy1=Integer.parseInt(yyyy1);
                                        LocalDate dob1 = LocalDate.of(yyyyy1,mmm1,ddd1);
                                        LocalDate curDate1 = LocalDate.now();
                                        Period period1 = Period.between(dob1, curDate1);
                                        String ab1=Integer.toString(period1.getDays());
                                        int ab=Integer.parseInt(ab1);

                                        if (code.length() <=0 || subject.length() <=0 || imaxmarks<=0 || iobtained<=0 || imaxmarks<iobtained || ab<0){

                                                JOptionPane.showMessageDialog(null,"Invalid Data");
                                        }
                                        else{
                                                try(Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
                                                        Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                                                ) {
                                                        String sql = "select * from Exam where code='"+code+"'";
                                                        ResultSet rs= stmt.executeQuery(sql);

                                                        if (!rs.first()){

                                                                try(Connection con = DriverManager.getConnection(DB_URL, USER, PASS);
                                                                        Statement stm = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                                                                )    {

                                                                        String sq = "Insert INTO Exam VALUES('"+code+"','"+subject+"','"+dateofexam+"','"+maxmarks+"','"+obtained+"')";

                                                                        stm.executeUpdate(sq);

                                                                        jTextField1.setText("");
                                                                        jTextField2.setText("");
                                                                        jDateChooser1.setDate(null);
                                                                        jSpinner1.setValue(0);
                                                                        jSpinner2.setValue(0);

                                                                        JOptionPane.showMessageDialog(null,"Successfully Added");

                                                                }
                                                                catch (SQLException e) {
                                                                        e.printStackTrace();
                                                                }
                                                        }
                                                        else{
                                                                JOptionPane.showMessageDialog(null,"Examination code already exists");
                                                        }

                                                }
                                                catch (SQLException e) {
                                                        e.printStackTrace();
                                                }
                                        }
                                }
                                catch (Exception e){
                                }
                        }
                        else{
                                JOptionPane.showMessageDialog(null,"Invalid Data");
                        }

                }
        }//GEN-LAST:event_jButton3ActionPerformed

        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                setVisible(false);
                new Homepage().setVisible(true);
                // TODO add your handling code here:
        }//GEN-LAST:event_jButton4ActionPerformed

        private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                int a=JOptionPane.showConfirmDialog(null,"Are you sure you want to close?","Select",JOptionPane.YES_NO_OPTION);
                if(a==0){
                        System.exit(0);
                }
                // TODO add your handling code here:
        }//GEN-LAST:event_jButton5ActionPerformed

        private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

                if(jDateChooser2.getDate()==null) {
                        JOptionPane.showMessageDialog(null,"Please fill in all the details");
                }
                else            {
                        String code=jTextField3.getText();
                        String subject=jTextField4.getText();
                        String dateofexam=(new java.text.SimpleDateFormat("dd-MM-yyyy")).format(jDateChooser2.getDate());
                        int imaxmarks=(int) jSpinner3.getValue();
                        int iobtained=(int) jSpinner4.getValue();
                        String maxmarks=Integer.toString(imaxmarks);
                        String obtained=Integer.toString(iobtained);
                        boolean result1 = subject.matches("[a-zA-Z ]+");

                        if (result1 && maxmarks.matches("[0-9]+") && obtained.matches("[0-9]+")){

                                try{
                                        SimpleDateFormat sdformat = new SimpleDateFormat("dd-MM-yyyy");
                                        Date d1 = sdformat.parse(dateofexam);

                                        String dd1=(new java.text.SimpleDateFormat("dd")).format(jDateChooser2.getDate());
                                        String mm1=(new java.text.SimpleDateFormat("MM")).format(jDateChooser2.getDate());
                                        String yyyy1=(new java.text.SimpleDateFormat("yyyy")).format(jDateChooser2.getDate());
                                        int ddd1=Integer.parseInt(dd1);
                                        int mmm1=Integer.parseInt(mm1);
                                        int yyyyy1=Integer.parseInt(yyyy1);
                                        LocalDate dob1 = LocalDate.of(yyyyy1,mmm1,ddd1);
                                        LocalDate curDate1 = LocalDate.now();
                                        Period period1 = Period.between(dob1, curDate1);
                                        String ab1=Integer.toString(period1.getDays());
                                        int ab=Integer.parseInt(ab1);

                                        if (code.length() <=0 || subject.length() <=0 || imaxmarks<=0 || iobtained<=0 || imaxmarks<iobtained || ab<0){

                                                JOptionPane.showMessageDialog(null,"Invalid Data");
                                        }
                                        else{
                                                try(Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
                                                        Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                                                ) {
                                                        String sql = "select * from Exam where code='"+code+"'";
                                                        ResultSet rs= stmt.executeQuery(sql);

                                                        if (!rs.first()){

                                                                
								JOptionPane.showMessageDialog(null,"Examination code does not exist");
                                                        }
                                                        else{
								try(Connection con = DriverManager.getConnection(DB_URL, USER, PASS);
                                                                        Statement stm = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                                                                )    {

                                                                        String sq = "update Exam set subject='"+subject+"', dateofexam='"+dateofexam+"', maxmarks='"+maxmarks+"', marksobtained='"+obtained+"' where code='"+code+"'";

                                                                        stm.executeUpdate(sq);

                                                                        jTextField3.setText("");
                                                                        jTextField4.setText("");
                                                                        jDateChooser2.setDate(null);
                                                                        jSpinner3.setValue(0);
                                                                        jSpinner4.setValue(0);
									jButton6.setVisible(false);

                                                                        JOptionPane.showMessageDialog(null,"Successfully Edited");

                                                                }
                                                                catch (SQLException e) {
                                                                        e.printStackTrace();
                                                                }
                                                                
                                                        }

                                                }
                                                catch (SQLException e) {
                                                        e.printStackTrace();
                                                }
                                        }
                                }
                                catch (Exception e){
                                }
                        }
                        else{
                                JOptionPane.showMessageDialog(null,"Invalid Data");
                        }

                }
        }//GEN-LAST:event_jButton6ActionPerformed

        private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
		String code=jTextField3.getText();
		if (code.length() <=0){
			JOptionPane.showMessageDialog(null,"Please enter an assignment code");
		}
		else{
			try(Connection con = DriverManager.getConnection(DB_URL, USER, PASS);
					Statement stm = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);	
					) { 
					String sq = "select * from Exam where code='"+code+"'";
                                        ResultSet rs1= stm.executeQuery(sq);
					if (!rs1.first()){
						JOptionPane.showMessageDialog(null,"Examination code does not exist");
					}
					else{
						jButton6.setVisible(true);
						try(Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
							Statement stmt = conn.createStatement();
							) {
							String sql = "select code, subject, dateofexam, maxmarks, marksobtained from Exam where code='"+code+"'";
							ResultSet rs= stmt.executeQuery(sql);
							while(rs.next()){
								String subject=rs.getString("subject");
								String dateofexam=rs.getString("dateofexam");
								String maxmarks=rs.getString("maxmarks");
								String marksobtained=rs.getString("marksobtained");
								jTextField4.setText(subject);
								
								
								try{
			                                        Date date = new SimpleDateFormat("dd-MM-yyyy").parse(dateofexam);
								jDateChooser2.setDate(date);
								int imaxmarks=Integer.parseInt(maxmarks);
								int imarksobtained=Integer.parseInt(marksobtained);  
								jSpinner3.setValue(imaxmarks);
							        jSpinner4.setValue(imarksobtained);
								}
								catch(Exception e){
								} 
								
								
							}
						}
						catch (SQLException e) { 
					e.printStackTrace();
						}
					}
			}
			catch (SQLException e) { 
					e.printStackTrace();
				 }
		}
                // TODO add your handling code here:
        }//GEN-LAST:event_jButton7ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EditExamination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EditExamination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EditExamination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EditExamination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new EditExamination().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JButton jButton5;
        private javax.swing.JButton jButton6;
        private javax.swing.JButton jButton7;
        private com.toedter.calendar.JDateChooser jDateChooser1;
        private com.toedter.calendar.JDateChooser jDateChooser2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JSpinner jSpinner1;
        private javax.swing.JSpinner jSpinner2;
        private javax.swing.JSpinner jSpinner3;
        private javax.swing.JSpinner jSpinner4;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField2;
        private javax.swing.JTextField jTextField3;
        private javax.swing.JTextField jTextField4;
        // End of variables declaration//GEN-END:variables
}
